FROM registry.access.redhat.com/jboss-eap-7/eap71-openshift
LABEL maintainer="xmigrate.cloud"
{% for artifact in artifacts.APP_DIR %}
COPY {{ artifact }} standalone/deployments
{% endfor %}
COPY {{ artifacts.APP_CONFIG }} /bin/standalone/configuration/standalone.xml
EXPOSE {{ artifacts.APP_PORT }}
CMD ["standalone.sh", "run"]