FROM tomcat
LABEL maintainer="josukutty"
{% for artifact in artifacts.APP_DIR %}
COPY {{ artifact }} /usr/local/tomcat/webapps
{% endfor %}
COPY {{ artifacts.APP_CONFIG }} /usr/local/tomcat/conf/tomcat-users.xml
EXPOSE {{ artifacts.APP_PORT }}
CMD ["catalina.sh", "run"]